
// This file has been generated by the GUI designer. Do not modify.
namespace lab8
{
	public partial class Window2
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView ViewTree2;

		private global::Gtk.Button Back2;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget lab8.Window2
			this.Name = "lab8.Window2";
			this.Title = global::Mono.Unix.Catalog.GetString("Window2");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.DestroyWithParent = true;
			// Container child lab8.Window2.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.ViewTree2 = new global::Gtk.TreeView();
			this.ViewTree2.CanFocus = true;
			this.ViewTree2.Name = "ViewTree2";
			this.GtkScrolledWindow.Add(this.ViewTree2);
			this.vbox1.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.GtkScrolledWindow]));
			w2.Position = 0;
			// Container child vbox1.Gtk.Box+BoxChild
			this.Back2 = new global::Gtk.Button();
			this.Back2.CanFocus = true;
			this.Back2.Name = "Back2";
			this.Back2.UseUnderline = true;
			this.Back2.Label = global::Mono.Unix.Catalog.GetString("Back");
			this.vbox1.Add(this.Back2);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.Back2]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Hide();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
			this.ViewTree2.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnViewTree2DeleteEvent);
			this.Back2.Clicked += new global::System.EventHandler(this.OnBack2Clicked);
		}
	}
}
