
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Frame frame1;

	private global::Gtk.Alignment GtkAlignment;

	private global::Gtk.Fixed panel1;

	private global::Gtk.Button ViewButton;

	private global::Gtk.Label label1;

	private global::Gtk.Button AddButton;

	private global::Gtk.Fixed fixed1;

	private global::Gtk.Entry NameBox;

	private global::Gtk.ComboBox Typebox;

	private global::Gtk.Label NameLabel;

	private global::Gtk.Label TypeLabeld;

	private global::Gtk.Label OwnerLabel;

	private global::Gtk.Entry OwnerBox;

	private global::Gtk.Button DoneButton;

	private global::Gtk.Button BackButton;

	private global::Gtk.SpinButton ScreenSpin;

	private global::Gtk.Label ScreenLabel;

	private global::Gtk.CheckButton ExTablesButton;

	private global::Gtk.ComboBoxEntry CatBox;

	private global::Gtk.Label CatLabel;

	private global::Gtk.Label ExcLabel;

	private global::Gtk.Label HoursLabel;

	private global::Gtk.Entry HoursBox;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Gravity = ((global::Gdk.Gravity)(8));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.frame1 = new global::Gtk.Frame();
		this.frame1.Name = "frame1";
		this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame1.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(12));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.panel1 = new global::Gtk.Fixed();
		this.panel1.Name = "panel1";
		this.panel1.HasWindow = false;
		// Container child panel1.Gtk.Fixed+FixedChild
		this.ViewButton = new global::Gtk.Button();
		this.ViewButton.CanFocus = true;
		this.ViewButton.Name = "ViewButton";
		this.ViewButton.UseUnderline = true;
		this.ViewButton.Label = global::Mono.Unix.Catalog.GetString("View");
		this.panel1.Add(this.ViewButton);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.panel1[this.ViewButton]));
		w1.X = 284;
		w1.Y = 274;
		// Container child panel1.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Mall Andes");
		this.panel1.Add(this.label1);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.panel1[this.label1]));
		w2.X = 18;
		w2.Y = 14;
		// Container child panel1.Gtk.Fixed+FixedChild
		this.AddButton = new global::Gtk.Button();
		this.AddButton.CanFocus = true;
		this.AddButton.Events = ((global::Gdk.EventMask)(256));
		this.AddButton.Name = "AddButton";
		this.AddButton.UseUnderline = true;
		this.AddButton.Label = global::Mono.Unix.Catalog.GetString("Add");
		this.panel1.Add(this.AddButton);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.panel1[this.AddButton]));
		w3.X = 41;
		w3.Y = 274;
		// Container child panel1.Gtk.Fixed+FixedChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		this.panel1.Add(this.fixed1);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.panel1[this.fixed1]));
		w4.X = 312;
		w4.Y = 185;
		// Container child panel1.Gtk.Fixed+FixedChild
		this.NameBox = new global::Gtk.Entry();
		this.NameBox.CanFocus = true;
		this.NameBox.Name = "NameBox";
		this.NameBox.IsEditable = true;
		this.NameBox.InvisibleChar = '●';
		this.panel1.Add(this.NameBox);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.panel1[this.NameBox]));
		w5.X = 138;
		w5.Y = 35;
		// Container child panel1.Gtk.Fixed+FixedChild
		this.Typebox = global::Gtk.ComboBox.NewText();
		this.Typebox.AppendText(global::Mono.Unix.Catalog.GetString("Type of local"));
		this.Typebox.AppendText(global::Mono.Unix.Catalog.GetString("Cine"));
		this.Typebox.AppendText(global::Mono.Unix.Catalog.GetString("Hobbie"));
		this.Typebox.AppendText(global::Mono.Unix.Catalog.GetString("Restaurant"));
		this.Typebox.AppendText(global::Mono.Unix.Catalog.GetString("Store"));
		this.Typebox.Name = "Typebox";
		this.Typebox.Active = 0;
		this.panel1.Add(this.Typebox);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.panel1[this.Typebox]));
		w6.X = 141;
		w6.Y = 90;
		// Container child panel1.Gtk.Fixed+FixedChild
		this.NameLabel = new global::Gtk.Label();
		this.NameLabel.Name = "NameLabel";
		this.NameLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Name");
		this.panel1.Add(this.NameLabel);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.panel1[this.NameLabel]));
		w7.X = 30;
		w7.Y = 38;
		// Container child panel1.Gtk.Fixed+FixedChild
		this.TypeLabeld = new global::Gtk.Label();
		this.TypeLabeld.Name = "TypeLabeld";
		this.TypeLabeld.LabelProp = global::Mono.Unix.Catalog.GetString("Type");
		this.panel1.Add(this.TypeLabeld);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.panel1[this.TypeLabeld]));
		w8.X = 30;
		w8.Y = 96;
		// Container child panel1.Gtk.Fixed+FixedChild
		this.OwnerLabel = new global::Gtk.Label();
		this.OwnerLabel.Name = "OwnerLabel";
		this.OwnerLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Owner");
		this.panel1.Add(this.OwnerLabel);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.panel1[this.OwnerLabel]));
		w9.X = 30;
		w9.Y = 129;
		// Container child panel1.Gtk.Fixed+FixedChild
		this.OwnerBox = new global::Gtk.Entry();
		this.OwnerBox.CanFocus = true;
		this.OwnerBox.Name = "OwnerBox";
		this.OwnerBox.IsEditable = true;
		this.OwnerBox.InvisibleChar = '●';
		this.panel1.Add(this.OwnerBox);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.panel1[this.OwnerBox]));
		w10.X = 138;
		w10.Y = 126;
		// Container child panel1.Gtk.Fixed+FixedChild
		this.DoneButton = new global::Gtk.Button();
		this.DoneButton.CanFocus = true;
		this.DoneButton.Name = "DoneButton";
		this.DoneButton.UseUnderline = true;
		this.DoneButton.Label = global::Mono.Unix.Catalog.GetString("Add local");
		this.panel1.Add(this.DoneButton);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.panel1[this.DoneButton]));
		w11.X = 212;
		w11.Y = 274;
		// Container child panel1.Gtk.Fixed+FixedChild
		this.BackButton = new global::Gtk.Button();
		this.BackButton.CanFocus = true;
		this.BackButton.Name = "BackButton";
		this.BackButton.UseUnderline = true;
		this.BackButton.Label = global::Mono.Unix.Catalog.GetString("Back");
		this.panel1.Add(this.BackButton);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.panel1[this.BackButton]));
		w12.X = 82;
		w12.Y = 274;
		// Container child panel1.Gtk.Fixed+FixedChild
		this.ScreenSpin = new global::Gtk.SpinButton(0D, 100D, 1D);
		this.ScreenSpin.CanFocus = true;
		this.ScreenSpin.Name = "ScreenSpin";
		this.ScreenSpin.Adjustment.PageIncrement = 10D;
		this.ScreenSpin.ClimbRate = 1D;
		this.ScreenSpin.Numeric = true;
		this.panel1.Add(this.ScreenSpin);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.panel1[this.ScreenSpin]));
		w13.X = 138;
		w13.Y = 160;
		// Container child panel1.Gtk.Fixed+FixedChild
		this.ScreenLabel = new global::Gtk.Label();
		this.ScreenLabel.Name = "ScreenLabel";
		this.ScreenLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Screens");
		this.panel1.Add(this.ScreenLabel);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.panel1[this.ScreenLabel]));
		w14.X = 30;
		w14.Y = 164;
		// Container child panel1.Gtk.Fixed+FixedChild
		this.ExTablesButton = new global::Gtk.CheckButton();
		this.ExTablesButton.CanFocus = true;
		this.ExTablesButton.Name = "ExTablesButton";
		this.ExTablesButton.Label = "";
		this.ExTablesButton.DrawIndicator = true;
		this.ExTablesButton.UseUnderline = true;
		this.panel1.Add(this.ExTablesButton);
		global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.panel1[this.ExTablesButton]));
		w15.X = 132;
		w15.Y = 188;
		// Container child panel1.Gtk.Fixed+FixedChild
		this.CatBox = global::Gtk.ComboBoxEntry.NewText();
		this.CatBox.Name = "CatBox";
		this.panel1.Add(this.CatBox);
		global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.panel1[this.CatBox]));
		w16.X = 138;
		w16.Y = 216;
		// Container child panel1.Gtk.Fixed+FixedChild
		this.CatLabel = new global::Gtk.Label();
		this.CatLabel.Name = "CatLabel";
		this.CatLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Categories");
		this.panel1.Add(this.CatLabel);
		global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.panel1[this.CatLabel]));
		w17.X = 30;
		w17.Y = 225;
		// Container child panel1.Gtk.Fixed+FixedChild
		this.ExcLabel = new global::Gtk.Label();
		this.ExcLabel.Name = "ExcLabel";
		this.ExcLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Exclusive Tables");
		this.panel1.Add(this.ExcLabel);
		global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.panel1[this.ExcLabel]));
		w18.X = 30;
		w18.Y = 194;
		// Container child panel1.Gtk.Fixed+FixedChild
		this.HoursLabel = new global::Gtk.Label();
		this.HoursLabel.Name = "HoursLabel";
		this.HoursLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Bussiness Hours");
		this.panel1.Add(this.HoursLabel);
		global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.panel1[this.HoursLabel]));
		w19.X = 30;
		w19.Y = 67;
		// Container child panel1.Gtk.Fixed+FixedChild
		this.HoursBox = new global::Gtk.Entry();
		this.HoursBox.CanFocus = true;
		this.HoursBox.Name = "HoursBox";
		this.HoursBox.IsEditable = true;
		this.HoursBox.InvisibleChar = '●';
		this.panel1.Add(this.HoursBox);
		global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.panel1[this.HoursBox]));
		w20.X = 138;
		w20.Y = 64;
		this.GtkAlignment.Add(this.panel1);
		this.frame1.Add(this.GtkAlignment);
		this.Add(this.frame1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 390;
		this.DefaultHeight = 351;
		this.NameBox.Hide();
		this.Typebox.Hide();
		this.NameLabel.Hide();
		this.TypeLabeld.Hide();
		this.OwnerLabel.Hide();
		this.OwnerBox.Hide();
		this.DoneButton.Hide();
		this.BackButton.Hide();
		this.ScreenSpin.Hide();
		this.ScreenLabel.Hide();
		this.ExTablesButton.Hide();
		this.CatBox.Hide();
		this.CatLabel.Hide();
		this.ExcLabel.Hide();
		this.HoursLabel.Hide();
		this.HoursBox.Hide();
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.ViewButton.Clicked += new global::System.EventHandler(this.OnViewButtonClicked);
		this.AddButton.Clicked += new global::System.EventHandler(this.OnAddButtonClicked);
		this.Typebox.Changed += new global::System.EventHandler(this.OnTypeboxChanged);
		this.DoneButton.Clicked += new global::System.EventHandler(this.OnDoneButtonClicked);
		this.BackButton.Clicked += new global::System.EventHandler(this.OnBackButtonClicked);
	}
}
